---
- name: Ensure cluster wildcard certificate namespace exists
  delegate_to: localhost
  when:
    - cert.namespace.create | default(true)
    - k3s.wildcards is defined
  kubernetes.core.k8s:
    context: "{{ context }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ cert.namespace.name }}"
  run_once: true
  loop: "{{ k3s.wildcards }}"
  loop_control:
    loop_var: cert

- name: Generate cluster wildcard certificate
  delegate_to: localhost
  ansible.builtin.template:
    src: wildcard-internal.yml.j2
    dest: /tmp/wildcard-{{ cert.name }}.yml
    mode: "0644"
  run_once: true
  loop: "{{ k3s.wildcards }}"
  loop_control:
    loop_var: cert

- name: Apply cluster wildcard certificate
  delegate_to: localhost
  kubernetes.core.k8s:
    src: /tmp/wildcard-{{ cert.name }}.yml
    state: present
  run_once: true
  loop: "{{ k3s.wildcards }}"
  loop_control:
    loop_var: cert
